name: "Lintme Action"
description: "A GitHub action to perform Lintme checks automatically."
author: "Dart Code Checker team"

branding:
  color: "blue"
  icon: "search"

inputs:
  github_token:
    description: "Token to connect to GitHub. Use secrets.GITHUB_TOKEN."
    required: true
  github_pat:
    description: "Personal access token. Required if you had private GitHub repository in the package dependencies."
    required: false
    default: ""
  folders:
    description: "List of folders whose contents will be scanned."
    required: false
    default: "lib"
  relative_path:
    description: "Path of the package relatively to the root of the repository."
    required: false
    default: ""
  pull_request_comment:
    description: "Publish detailed report commented directly into your pull request."
    required: false
    default: "false"
  analyze_report_title_pattern:
    description: "Configurable analyze report title pattern."
    required: false
    default: "Lintme analyze report of $packageName."
  fatal_warnings:
    description: "Treat warning level issues as fatal."
    required: false
    default: "false"
  fatal_performance:
    description: "Treat performance level issues as fatal."
    required: false
    default: "false"
  fatal_style:
    description: "Treat style level issues as fatal."
    required: false
    default: "false"
  check_unused_files:
    description: "Additional scan for find unused files in package."
    required: false
    default: "false"
  check_unused_files_folders:
    description: "List of folders whose contents will be scanned for find unused files."
    required: false
  unused_files_report_title_pattern:
    description: "Configurable unused files report title pattern."
    required: false
    default: "Lintme unused files report of $packageName."

runs:
  using: "docker"
  image: "Dockerfile"
