name: action_app
version: 1.0.0
description: Github action app that helps to run lintme in CI/CD flow.
repository: https://github.com/danylo-safonov-solid/lintme-action
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  actions_toolkit_dart: ^0.5.1
  github: ^9.24.0
  lintme: 1.0.0+1
  meta: ^1.15.0
  path: ^1.9.0

dependency_overrides:
  watcher: ^1.1.0

dev_dependencies:
  coverage: ^1.9.2
  lints: ^4.0.0
  mocktail: ^1.0.4
  source_span: ^1.10.0
  test: ^1.25.7
